name: API builder
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  CI: true

jobs:
  gradle-build:
    name: Gradle build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run test
        run: ./api/gradlew -p api/ test --stacktrace

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: api/build/reports/tests/test

      - name: Run integration test
        run: ./api/gradlew -p api/ integrationTest --stacktrace

      - name: Archive integration test report
        uses: actions/upload-artifact@v2
        with:
          name: Integration test report
          path: api/build/reports/tests/integrationTest

      - name: Run assemble
        run: ./api/gradlew -p api/ assemble --stacktrace

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: api/build/libs

  docker-build:
    name: Docker build and push image
    runs-on: ubuntu-latest
    needs:
      - gradle-build
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: build_artifacts
          path: api/build/libs

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/rassafel/todo-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
