name: API builder
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./api/gradlew -p api/ assemble --no-daemon
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build artifacts
          path: api/build/libs

      - name: Run test with Gradle Wrapper
        run: ./api/gradlew -p api/ test --no-daemon
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: api/build/reports/tests/test

      - name: Run test with Gradle Wrapper
        run: ./api/gradlew -p api/ integrationTest --no-daemon
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Integration test report
          path: api/build/reports/tests/integrationTest

      - name: Prepare to build image
        run: |
          DOCKER_IMAGE=ghcr.io/rassafel/todo-api
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
